name: Mirror upstream CLDR  # creates cldr-upstream branch and strip mirroted workflows

on:
  schedule:
    - cron: '0 0 1 * *'    # monthly, 1st at 00:00 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine upstream default branch
        id: upstream
        shell: bash
        run: |
          set -euo pipefail
          UPSTREAM="https://github.com/unicode-org/cldr.git"
          # Figure out upstream's default branch name reliably
          DEF_REF="$(git ls-remote --symref "$UPSTREAM" HEAD | awk '/^ref:/ {print $2}')"
          DEF_BRANCH="${DEF_REF#refs/heads/}"
          echo "default=$DEF_BRANCH" >> "$GITHUB_OUTPUT"

      - name: Fetch upstream tip
        shell: bash
        run: |
          set -euo pipefail
          UPSTREAM="https://github.com/unicode-org/cldr.git"
          BR="${{ steps.upstream.outputs.default }}"
          git fetch "$UPSTREAM" "refs/heads/$BR:refs/remotes/upstream/$BR"

      - name: Create/update cldr-upstream branch & strip upstream workflows
        shell: bash
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          SRC="refs/remotes/upstream/${{ steps.upstream.outputs.default }}"
          TARGET="cldr-upstream"

          # Create/reset local branch to upstream tip
          git checkout -B "$TARGET" "$SRC"

          # Remove any upstream workflow files so push doesn't require workflows:write
          if [ -d ".github/workflows" ]; then
            git rm -r --quiet .github/workflows || true
          fi

          # Commit only if there are changes after removal
          if ! git diff --quiet; then
            git commit -m "Strip upstream workflows for safe mirror"
          fi

          # Force-push the sanitized branch
          git push -f origin "$TARGET"
